package constant

const (
	LEAVE_APPROVE   = "APPROVE"
	LEAVE_REJECT    = "REJECT"
	LEAVE_APPLOVED  = "APPROVED"
	LEAVE_REJECTED  = "REJECTED"
	LEAVE_CANCELLED = "CANCELLED"

	LEAVE_MANAGER_REJECTED = "MANAGER_REJECTED"
	LEAVE_MANAGER_APPROVED = "MANAGER_APPROVED"

	LEAVE_WITHDRAWAL_PENDING = "WITHDRAWAL_PENDING"
	LEAVE_WITHDRAWN          = "WITHDRAWN"
)

const (
	ROLE_SUPER_ADMIN = "SUPERADMIN"
	ROLE_ADMIN       = "ADMIN"
	ROLE_EMPLOYEE    = "EMPLOYEE"
	ROLE_MANAGER     = "MANAGER"
	ROLE_HR          = "HR"
)
